-- ═══════════════════════════════════════════════════════════════════════════
-- WORKFORCE ACCELERATOR - INVITE LINK EXPIRATION
-- ═══════════════════════════════════════════════════════════════════════════
--
-- This migration adds expiration timestamps to invite codes.
-- Invite links expire after 24 hours and can be regenerated by admins.
-- ═══════════════════════════════════════════════════════════════════════════

-- Add expiration column to organizations table
ALTER TABLE organizations
ADD COLUMN invite_code_expires_at TIMESTAMPTZ;

-- Set existing invite codes to expire 24 hours from now (for existing orgs)
UPDATE organizations
SET invite_code_expires_at = NOW() + INTERVAL '24 hours'
WHERE invite_code_expires_at IS NULL;

-- Make the column NOT NULL after setting defaults
ALTER TABLE organizations
ALTER COLUMN invite_code_expires_at SET NOT NULL;

-- Add index for efficient expiration queries
CREATE INDEX idx_organizations_invite_expires ON organizations(invite_code_expires_at);
