-- ═══════════════════════════════════════════════════════════════════════════
-- WORKFORCE ACCELERATOR - TIMEKEEPING JOURNAL TABLES
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- JOURNAL ENTRIES TABLE (user interaction diary per prospect)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS lead_agent_journal_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    prospect_id UUID NOT NULL REFERENCES lead_agent_prospects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Entry Content
    content TEXT NOT NULL,
    interaction_type TEXT NOT NULL DEFAULT 'note'
        CHECK (interaction_type IN ('call', 'email', 'whatsapp', 'meeting', 'text', 'note', 'other')),

    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_journal_entries_prospect_id ON lead_agent_journal_entries(prospect_id);
CREATE INDEX IF NOT EXISTS idx_journal_entries_user_id ON lead_agent_journal_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_journal_entries_created_at ON lead_agent_journal_entries(created_at DESC);

-- Apply updated_at trigger (drop first if exists to avoid errors)
DROP TRIGGER IF EXISTS update_journal_entries_updated_at ON lead_agent_journal_entries;
CREATE TRIGGER update_journal_entries_updated_at BEFORE UPDATE ON lead_agent_journal_entries
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ─────────────────────────────────────────────────────────────────────────────
-- SCHEDULED NOTIFICATIONS TABLE (AI-generated follow-up reminders)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS lead_agent_scheduled_notifications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    prospect_id UUID NOT NULL REFERENCES lead_agent_prospects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Notification Content (generated by AI)
    message TEXT NOT NULL,

    -- Scheduling
    scheduled_for TIMESTAMPTZ NOT NULL,

    -- Status Tracking
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'sent', 'cancelled')),
    sent_at TIMESTAMPTZ,

    -- AI Reasoning (stored for debugging, never shown to user)
    ai_reasoning TEXT,

    -- Reference to the journal entry that triggered this
    triggered_by_entry_id UUID REFERENCES lead_agent_journal_entries(id) ON DELETE SET NULL,

    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON lead_agent_scheduled_notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_prospect_id ON lead_agent_scheduled_notifications(prospect_id);
CREATE INDEX IF NOT EXISTS idx_notifications_scheduled ON lead_agent_scheduled_notifications(scheduled_for)
    WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_notifications_status ON lead_agent_scheduled_notifications(status);

-- Apply updated_at trigger (drop first if exists to avoid errors)
DROP TRIGGER IF EXISTS update_notifications_updated_at ON lead_agent_scheduled_notifications;
CREATE TRIGGER update_notifications_updated_at BEFORE UPDATE ON lead_agent_scheduled_notifications
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ─────────────────────────────────────────────────────────────────────────────
-- ENABLE ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE lead_agent_journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE lead_agent_scheduled_notifications ENABLE ROW LEVEL SECURITY;

-- Deny all access for anon role (service role bypasses RLS)
-- Drop existing policies first to avoid conflicts
DROP POLICY IF EXISTS "Deny all for anon on lead_agent_journal_entries" ON lead_agent_journal_entries;
CREATE POLICY "Deny all for anon on lead_agent_journal_entries"
    ON lead_agent_journal_entries TO anon USING (false);

DROP POLICY IF EXISTS "Deny all for anon on lead_agent_scheduled_notifications" ON lead_agent_scheduled_notifications;
CREATE POLICY "Deny all for anon on lead_agent_scheduled_notifications"
    ON lead_agent_scheduled_notifications TO anon USING (false);
